version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "12:00"
      timezone: Europe/London
    labels: []
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "12:00"
      timezone: Europe/London
    labels: []
